from typing import Literal as Lit


TP = Lit[
    'High LS Rtn Rank',
    'High LS Rtn +1Y',
    'High LS Rtn +3Y',
    'High LS Rtn +5Y',
    'High LS Rtn +10Y',
    'High LS Rtn +20Y',
    'High LS Rtn +40Y',
    'High Cor Rank',
    'High Cor 1Y',
    'High Cor 3Y',
    'High Cor 5Y',
    'High Cor 10Y',
    'High Cor 20Y',
    'High Cor 40Y',
    'High Rank',
    'Low Rank',
    'High Gap',
    'Low Gap',
    'High Gap 1Y',
    'Low Gap 1Y',
    'High Gap 3Y',
    'Low Gap 3Y',
    'High Gap 5Y',
    'Low Gap 5Y',
    'High Gap 10Y',
    'Low Gap 10Y',
    'High Gap 20Y',
    'Low Gap 20Y',
    'High Gap 40Y',
    'Low Gap 40Y',
    'High Gap Abs',
    'Low Gap Abs',
    'High Gap Abs 1Y',
    'Low Gap Abs 1Y',
    'High Gap Abs 3Y',
    'Low Gap Abs 3Y',
    'High Gap Abs 5Y',
    'Low Gap Abs 5Y',
    'High Gap Abs 10Y',
    'Low Gap Abs 10Y',
    'High Gap Abs 20Y',
    'Low Gap Abs 20Y',
    'High Gap Abs 40Y',
    'Low Gap Abs 40Y',
    'High Gap Avg',
    'Low Gap Avg',
    'High Gap.1 Avg.1',
    'Low Gap.1 Avg.1',
    'High Gap.1 Avg.3',
    'Low Gap.1 Avg.3',
    'High Gap.1 Avg.5',
    'Low Gap.1 Avg.5',
    'High Gap.1 Avg.10',
    'Low Gap.1 Avg.10',
    'High Gap.1 Avg.20',
    'Low Gap.1 Avg.20',
    'High Gap.1 Avg.40',
    'Low Gap.1 Avg.40',
    'High Gap.3 Avg.1',
    'Low Gap.3 Avg.1',
    'High Gap.3 Avg.3',
    'Low Gap.3 Avg.3',
    'High Gap.3 Avg.5',
    'Low Gap.3 Avg.5',
    'High Gap.3 Avg.10',
    'Low Gap.3 Avg.10',
    'High Gap.3 Avg.20',
    'Low Gap.3 Avg.20',
    'High Gap.3 Avg.40',
    'Low Gap.3 Avg.40',
    'High Gap.5 Avg.1',
    'Low Gap.5 Avg.1',
    'High Gap.5 Avg.3',
    'Low Gap.5 Avg.3',
    'High Gap.5 Avg.5',
    'Low Gap.5 Avg.5',
    'High Gap.5 Avg.10',
    'Low Gap.5 Avg.10',
    'High Gap.5 Avg.20',
    'Low Gap.5 Avg.20',
    'High Gap.5 Avg.40',
    'Low Gap.5 Avg.40',
    'High Gap.10 Avg.1',
    'Low Gap.10 Avg.1',
    'High Gap.10 Avg.3',
    'Low Gap.10 Avg.3',
    'High Gap.10 Avg.5',
    'Low Gap.10 Avg.5',
    'High Gap.10 Avg.10',
    'Low Gap.10 Avg.10',
    'High Gap.10 Avg.20',
    'Low Gap.10 Avg.20',
    'High Gap.10 Avg.40',
    'Low Gap.10 Avg.40',
    'High Gap.20 Avg.1',
    'Low Gap.20 Avg.1',
    'High Gap.20 Avg.3',
    'Low Gap.20 Avg.3',
    'High Gap.20 Avg.5',
    'Low Gap.20 Avg.5',
    'High Gap.20 Avg.10',
    'Low Gap.20 Avg.10',
    'High Gap.20 Avg.20',
    'Low Gap.20 Avg.20',
    'High Gap.20 Avg.40',
    'Low Gap.20 Avg.40',
    'High Gap.40 Avg.1',
    'Low Gap.40 Avg.1',
    'High Gap.40 Avg.3',
    'Low Gap.40 Avg.3',
    'High Gap.40 Avg.5',
    'Low Gap.40 Avg.5',
    'High Gap.40 Avg.10',
    'Low Gap.40 Avg.10',
    'High Gap.40 Avg.20',
    'Low Gap.40 Avg.20',
    'High Gap.40 Avg.40',
    'Low Gap.40 Avg.40',
    'High Gap Dev',
    'Low Gap Dev',
    'High Gap.1 Dev.1',
    'Low Gap.1 Dev.1',
    'High Gap.1 Dev.3',
    'Low Gap.1 Dev.3',
    'High Gap.1 Dev.5',
    'Low Gap.1 Dev.5',
    'High Gap.1 Dev.10',
    'Low Gap.1 Dev.10',
    'High Gap.1 Dev.20',
    'Low Gap.1 Dev.20',
    'High Gap.1 Dev.40',
    'Low Gap.1 Dev.40',
    'High Gap.3 Dev.1',
    'Low Gap.3 Dev.1',
    'High Gap.3 Dev.3',
    'Low Gap.3 Dev.3',
    'High Gap.3 Dev.5',
    'Low Gap.3 Dev.5',
    'High Gap.3 Dev.10',
    'Low Gap.3 Dev.10',
    'High Gap.3 Dev.20',
    'Low Gap.3 Dev.20',
    'High Gap.3 Dev.40',
    'Low Gap.3 Dev.40',
    'High Gap.5 Dev.1',
    'Low Gap.5 Dev.1',
    'High Gap.5 Dev.3',
    'Low Gap.5 Dev.3',
    'High Gap.5 Dev.5',
    'Low Gap.5 Dev.5',
    'High Gap.5 Dev.10',
    'Low Gap.5 Dev.10',
    'High Gap.5 Dev.20',
    'Low Gap.5 Dev.20',
    'High Gap.5 Dev.40',
    'Low Gap.5 Dev.40',
    'High Gap.10 Dev.1',
    'Low Gap.10 Dev.1',
    'High Gap.10 Dev.3',
    'Low Gap.10 Dev.3',
    'High Gap.10 Dev.5',
    'Low Gap.10 Dev.5',
    'High Gap.10 Dev.10',
    'Low Gap.10 Dev.10',
    'High Gap.10 Dev.20',
    'Low Gap.10 Dev.20',
    'High Gap.10 Dev.40',
    'Low Gap.10 Dev.40',
    'High Gap.20 Dev.1',
    'Low Gap.20 Dev.1',
    'High Gap.20 Dev.3',
    'Low Gap.20 Dev.3',
    'High Gap.20 Dev.5',
    'Low Gap.20 Dev.5',
    'High Gap.20 Dev.10',
    'Low Gap.20 Dev.10',
    'High Gap.20 Dev.20',
    'Low Gap.20 Dev.20',
    'High Gap.20 Dev.40',
    'Low Gap.20 Dev.40',
    'High Gap.40 Dev.1',
    'Low Gap.40 Dev.1',
    'High Gap.40 Dev.3',
    'Low Gap.40 Dev.3',
    'High Gap.40 Dev.5',
    'Low Gap.40 Dev.5',
    'High Gap.40 Dev.10',
    'Low Gap.40 Dev.10',
    'High Gap.40 Dev.20',
    'Low Gap.40 Dev.20',
    'High Gap.40 Dev.40',
    'Low Gap.40 Dev.40',
    'High Gap Lvl',
    'Low Gap Lvl',
    'High Gap.1 Lvl.1',
    'Low Gap.1 Lvl.1',
    'High Gap.1 Lvl.3',
    'Low Gap.1 Lvl.3',
    'High Gap.1 Lvl.5',
    'Low Gap.1 Lvl.5',
    'High Gap.1 Lvl.10',
    'Low Gap.1 Lvl.10',
    'High Gap.1 Lvl.20',
    'Low Gap.1 Lvl.20',
    'High Gap.1 Lvl.40',
    'Low Gap.1 Lvl.40',
    'High Gap.3 Lvl.1',
    'Low Gap.3 Lvl.1',
    'High Gap.3 Lvl.3',
    'Low Gap.3 Lvl.3',
    'High Gap.3 Lvl.5',
    'Low Gap.3 Lvl.5',
    'High Gap.3 Lvl.10',
    'Low Gap.3 Lvl.10',
    'High Gap.3 Lvl.20',
    'Low Gap.3 Lvl.20',
    'High Gap.3 Lvl.40',
    'Low Gap.3 Lvl.40',
    'High Gap.5 Lvl.1',
    'Low Gap.5 Lvl.1',
    'High Gap.5 Lvl.3',
    'Low Gap.5 Lvl.3',
    'High Gap.5 Lvl.5',
    'Low Gap.5 Lvl.5',
    'High Gap.5 Lvl.10',
    'Low Gap.5 Lvl.10',
    'High Gap.5 Lvl.20',
    'Low Gap.5 Lvl.20',
    'High Gap.5 Lvl.40',
    'Low Gap.5 Lvl.40',
    'High Gap.10 Lvl.1',
    'Low Gap.10 Lvl.1',
    'High Gap.10 Lvl.3',
    'Low Gap.10 Lvl.3',
    'High Gap.10 Lvl.5',
    'Low Gap.10 Lvl.5',
    'High Gap.10 Lvl.10',
    'Low Gap.10 Lvl.10',
    'High Gap.10 Lvl.20',
    'Low Gap.10 Lvl.20',
    'High Gap.10 Lvl.40',
    'Low Gap.10 Lvl.40',
    'High Gap.20 Lvl.1',
    'Low Gap.20 Lvl.1',
    'High Gap.20 Lvl.3',
    'Low Gap.20 Lvl.3',
    'High Gap.20 Lvl.5',
    'Low Gap.20 Lvl.5',
    'High Gap.20 Lvl.10',
    'Low Gap.20 Lvl.10',
    'High Gap.20 Lvl.20',
    'Low Gap.20 Lvl.20',
    'High Gap.20 Lvl.40',
    'Low Gap.20 Lvl.40',
    'High Gap.40 Lvl.1',
    'Low Gap.40 Lvl.1',
    'High Gap.40 Lvl.3',
    'Low Gap.40 Lvl.3',
    'High Gap.40 Lvl.5',
    'Low Gap.40 Lvl.5',
    'High Gap.40 Lvl.10',
    'Low Gap.40 Lvl.10',
    'High Gap.40 Lvl.20',
    'Low Gap.40 Lvl.20',
    'High Gap.40 Lvl.40',
    'Low Gap.40 Lvl.40',
    'High Abs Gap',
    'Low Abs Gap',
    'High Abs Gap 1Y',
    'Low Abs Gap 1Y',
    'High Abs Gap 3Y',
    'Low Abs Gap 3Y',
    'High Abs Gap 5Y',
    'Low Abs Gap 5Y',
    'High Abs Gap 10Y',
    'Low Abs Gap 10Y',
    'High Abs Gap 20Y',
    'Low Abs Gap 20Y',
    'High Abs Gap 40Y',
    'Low Abs Gap 40Y',
    'High Abs Gap Abs',
    'Low Abs Gap Abs',
    'High Abs Gap Abs 1Y',
    'Low Abs Gap Abs 1Y',
    'High Abs Gap Abs 3Y',
    'Low Abs Gap Abs 3Y',
    'High Abs Gap Abs 5Y',
    'Low Abs Gap Abs 5Y',
    'High Abs Gap Abs 10Y',
    'Low Abs Gap Abs 10Y',
    'High Abs Gap Abs 20Y',
    'Low Abs Gap Abs 20Y',
    'High Abs Gap Abs 40Y',
    'Low Abs Gap Abs 40Y',
    'High Abs Gap Avg',
    'Low Abs Gap Avg',
    'High Abs Gap.1 Avg.1',
    'Low Abs Gap.1 Avg.1',
    'High Abs Gap.1 Avg.3',
    'Low Abs Gap.1 Avg.3',
    'High Abs Gap.1 Avg.5',
    'Low Abs Gap.1 Avg.5',
    'High Abs Gap.1 Avg.10',
    'Low Abs Gap.1 Avg.10',
    'High Abs Gap.1 Avg.20',
    'Low Abs Gap.1 Avg.20',
    'High Abs Gap.1 Avg.40',
    'Low Abs Gap.1 Avg.40',
    'High Abs Gap.3 Avg.1',
    'Low Abs Gap.3 Avg.1',
    'High Abs Gap.3 Avg.3',
    'Low Abs Gap.3 Avg.3',
    'High Abs Gap.3 Avg.5',
    'Low Abs Gap.3 Avg.5',
    'High Abs Gap.3 Avg.10',
    'Low Abs Gap.3 Avg.10',
    'High Abs Gap.3 Avg.20',
    'Low Abs Gap.3 Avg.20',
    'High Abs Gap.3 Avg.40',
    'Low Abs Gap.3 Avg.40',
    'High Abs Gap.5 Avg.1',
    'Low Abs Gap.5 Avg.1',
    'High Abs Gap.5 Avg.3',
    'Low Abs Gap.5 Avg.3',
    'High Abs Gap.5 Avg.5',
    'Low Abs Gap.5 Avg.5',
    'High Abs Gap.5 Avg.10',
    'Low Abs Gap.5 Avg.10',
    'High Abs Gap.5 Avg.20',
    'Low Abs Gap.5 Avg.20',
    'High Abs Gap.5 Avg.40',
    'Low Abs Gap.5 Avg.40',
    'High Abs Gap.10 Avg.1',
    'Low Abs Gap.10 Avg.1',
    'High Abs Gap.10 Avg.3',
    'Low Abs Gap.10 Avg.3',
    'High Abs Gap.10 Avg.5',
    'Low Abs Gap.10 Avg.5',
    'High Abs Gap.10 Avg.10',
    'Low Abs Gap.10 Avg.10',
    'High Abs Gap.10 Avg.20',
    'Low Abs Gap.10 Avg.20',
    'High Abs Gap.10 Avg.40',
    'Low Abs Gap.10 Avg.40',
    'High Abs Gap.20 Avg.1',
    'Low Abs Gap.20 Avg.1',
    'High Abs Gap.20 Avg.3',
    'Low Abs Gap.20 Avg.3',
    'High Abs Gap.20 Avg.5',
    'Low Abs Gap.20 Avg.5',
    'High Abs Gap.20 Avg.10',
    'Low Abs Gap.20 Avg.10',
    'High Abs Gap.20 Avg.20',
    'Low Abs Gap.20 Avg.20',
    'High Abs Gap.20 Avg.40',
    'Low Abs Gap.20 Avg.40',
    'High Abs Gap.40 Avg.1',
    'Low Abs Gap.40 Avg.1',
    'High Abs Gap.40 Avg.3',
    'Low Abs Gap.40 Avg.3',
    'High Abs Gap.40 Avg.5',
    'Low Abs Gap.40 Avg.5',
    'High Abs Gap.40 Avg.10',
    'Low Abs Gap.40 Avg.10',
    'High Abs Gap.40 Avg.20',
    'Low Abs Gap.40 Avg.20',
    'High Abs Gap.40 Avg.40',
    'Low Abs Gap.40 Avg.40',
    'High Abs Gap Dev',
    'Low Abs Gap Dev',
    'High Abs Gap.1 Dev.1',
    'Low Abs Gap.1 Dev.1',
    'High Abs Gap.1 Dev.3',
    'Low Abs Gap.1 Dev.3',
    'High Abs Gap.1 Dev.5',
    'Low Abs Gap.1 Dev.5',
    'High Abs Gap.1 Dev.10',
    'Low Abs Gap.1 Dev.10',
    'High Abs Gap.1 Dev.20',
    'Low Abs Gap.1 Dev.20',
    'High Abs Gap.1 Dev.40',
    'Low Abs Gap.1 Dev.40',
    'High Abs Gap.3 Dev.1',
    'Low Abs Gap.3 Dev.1',
    'High Abs Gap.3 Dev.3',
    'Low Abs Gap.3 Dev.3',
    'High Abs Gap.3 Dev.5',
    'Low Abs Gap.3 Dev.5',
    'High Abs Gap.3 Dev.10',
    'Low Abs Gap.3 Dev.10',
    'High Abs Gap.3 Dev.20',
    'Low Abs Gap.3 Dev.20',
    'High Abs Gap.3 Dev.40',
    'Low Abs Gap.3 Dev.40',
    'High Abs Gap.5 Dev.1',
    'Low Abs Gap.5 Dev.1',
    'High Abs Gap.5 Dev.3',
    'Low Abs Gap.5 Dev.3',
    'High Abs Gap.5 Dev.5',
    'Low Abs Gap.5 Dev.5',
    'High Abs Gap.5 Dev.10',
    'Low Abs Gap.5 Dev.10',
    'High Abs Gap.5 Dev.20',
    'Low Abs Gap.5 Dev.20',
    'High Abs Gap.5 Dev.40',
    'Low Abs Gap.5 Dev.40',
    'High Abs Gap.10 Dev.1',
    'Low Abs Gap.10 Dev.1',
    'High Abs Gap.10 Dev.3',
    'Low Abs Gap.10 Dev.3',
    'High Abs Gap.10 Dev.5',
    'Low Abs Gap.10 Dev.5',
    'High Abs Gap.10 Dev.10',
    'Low Abs Gap.10 Dev.10',
    'High Abs Gap.10 Dev.20',
    'Low Abs Gap.10 Dev.20',
    'High Abs Gap.10 Dev.40',
    'Low Abs Gap.10 Dev.40',
    'High Abs Gap.20 Dev.1',
    'Low Abs Gap.20 Dev.1',
    'High Abs Gap.20 Dev.3',
    'Low Abs Gap.20 Dev.3',
    'High Abs Gap.20 Dev.5',
    'Low Abs Gap.20 Dev.5',
    'High Abs Gap.20 Dev.10',
    'Low Abs Gap.20 Dev.10',
    'High Abs Gap.20 Dev.20',
    'Low Abs Gap.20 Dev.20',
    'High Abs Gap.20 Dev.40',
    'Low Abs Gap.20 Dev.40',
    'High Abs Gap.40 Dev.1',
    'Low Abs Gap.40 Dev.1',
    'High Abs Gap.40 Dev.3',
    'Low Abs Gap.40 Dev.3',
    'High Abs Gap.40 Dev.5',
    'Low Abs Gap.40 Dev.5',
    'High Abs Gap.40 Dev.10',
    'Low Abs Gap.40 Dev.10',
    'High Abs Gap.40 Dev.20',
    'Low Abs Gap.40 Dev.20',
    'High Abs Gap.40 Dev.40',
    'Low Abs Gap.40 Dev.40',
    'High Abs Gap Lvl',
    'Low Abs Gap Lvl',
    'High Abs Gap.1 Lvl.1',
    'Low Abs Gap.1 Lvl.1',
    'High Abs Gap.1 Lvl.3',
    'Low Abs Gap.1 Lvl.3',
    'High Abs Gap.1 Lvl.5',
    'Low Abs Gap.1 Lvl.5',
    'High Abs Gap.1 Lvl.10',
    'Low Abs Gap.1 Lvl.10',
    'High Abs Gap.1 Lvl.20',
    'Low Abs Gap.1 Lvl.20',
    'High Abs Gap.1 Lvl.40',
    'Low Abs Gap.1 Lvl.40',
    'High Abs Gap.3 Lvl.1',
    'Low Abs Gap.3 Lvl.1',
    'High Abs Gap.3 Lvl.3',
    'Low Abs Gap.3 Lvl.3',
    'High Abs Gap.3 Lvl.5',
    'Low Abs Gap.3 Lvl.5',
    'High Abs Gap.3 Lvl.10',
    'Low Abs Gap.3 Lvl.10',
    'High Abs Gap.3 Lvl.20',
    'Low Abs Gap.3 Lvl.20',
    'High Abs Gap.3 Lvl.40',
    'Low Abs Gap.3 Lvl.40',
    'High Abs Gap.5 Lvl.1',
    'Low Abs Gap.5 Lvl.1',
    'High Abs Gap.5 Lvl.3',
    'Low Abs Gap.5 Lvl.3',
    'High Abs Gap.5 Lvl.5',
    'Low Abs Gap.5 Lvl.5',
    'High Abs Gap.5 Lvl.10',
    'Low Abs Gap.5 Lvl.10',
    'High Abs Gap.5 Lvl.20',
    'Low Abs Gap.5 Lvl.20',
    'High Abs Gap.5 Lvl.40',
    'Low Abs Gap.5 Lvl.40',
    'High Abs Gap.10 Lvl.1',
    'Low Abs Gap.10 Lvl.1',
    'High Abs Gap.10 Lvl.3',
    'Low Abs Gap.10 Lvl.3',
    'High Abs Gap.10 Lvl.5',
    'Low Abs Gap.10 Lvl.5',
    'High Abs Gap.10 Lvl.10',
    'Low Abs Gap.10 Lvl.10',
    'High Abs Gap.10 Lvl.20',
    'Low Abs Gap.10 Lvl.20',
    'High Abs Gap.10 Lvl.40',
    'Low Abs Gap.10 Lvl.40',
    'High Abs Gap.20 Lvl.1',
    'Low Abs Gap.20 Lvl.1',
    'High Abs Gap.20 Lvl.3',
    'Low Abs Gap.20 Lvl.3',
    'High Abs Gap.20 Lvl.5',
    'Low Abs Gap.20 Lvl.5',
    'High Abs Gap.20 Lvl.10',
    'Low Abs Gap.20 Lvl.10',
    'High Abs Gap.20 Lvl.20',
    'Low Abs Gap.20 Lvl.20',
    'High Abs Gap.20 Lvl.40',
    'Low Abs Gap.20 Lvl.40',
    'High Abs Gap.40 Lvl.1',
    'Low Abs Gap.40 Lvl.1',
    'High Abs Gap.40 Lvl.3',
    'Low Abs Gap.40 Lvl.3',
    'High Abs Gap.40 Lvl.5',
    'Low Abs Gap.40 Lvl.5',
    'High Abs Gap.40 Lvl.10',
    'Low Abs Gap.40 Lvl.10',
    'High Abs Gap.40 Lvl.20',
    'Low Abs Gap.40 Lvl.20',
    'High Abs Gap.40 Lvl.40',
    'Low Abs Gap.40 Lvl.40', 
]

